function createDynareExperiment(folder, name)
%CREATE DYNARE EXPERIMENT Create a new Dynare experiment
%   createDynareExperiment(FOLDER) creates a new Dynare experiment in the
%   directory specified by FOLDER. FOLDER must be a scalar string
%   specifying the path to the destination folder.
%
%   createDynareExperiment(FOLDER, NAME) creates the project in a folder
%   named NAME within FOLDER. NAME must be a scalar string. If a folder
%   with the specified name already exists a unique name is generated by
%   appending _1, _2, etc.
%
%   Example:
%       createDynareExperiment("C:\Users\Me", "MyExperiment")
%
%   Inputs:
%       folder - (1,1) string scalar specifying the destination folder.
%       name   - (1,1) string scalar specifying the project folder name.
%
%   Notes:
%       - If the requested project folder already exists, a unique folder
%         name is generated by appending an underscore and a number.
%       - The function creates the folder and extracts a project template
%         into it.
%
%   See also matlab.project.extractProject, isfolder, mkdir

arguments
    folder (1,1) string {mustBeFolder}
    name (1,1) string = "DynareExperiment"
end

destination = fullfile(folder, name);
if isfolder(destination)
    destination_new = destination;
    count = 1;
    while isfolder(destination_new)
        destination_new = destination + "_" + count;
        count = count + 1; % Increment the count for the new folder name
    end
    destination = destination_new;
end

mkdir(destination)

matlab.project.extractProject(fullfile(dynareUtilsRoot, 'experiment','DynareExperiment.mlproj'), destination);
experiments.internal.View('project',fullfile(destination, 'DynareExperiment.prj'));